using NUnit.Framework;
using Moq;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis;
using TestsGenerator.Core;

namespace Tests
{
    [TestFixture]
    public class ClassDeclarationSyntaxExtensionsTests
    {
        [Test]
        public void GetConstructorWithMaxArgumentsCountTest()
        {
            ClassDeclarationSyntax syntaxFake = default;
            ConstructorDeclarationSyntax actual = ClassDeclarationSyntaxExtensions.GetConstructorWithMaxArgumentsCount(syntaxFake);
            ConstructorDeclarationSyntax expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

        [Test]
        public void GetPublicMethodsTest()
        {
            ClassDeclarationSyntax syntaxFake = default;
            object actual = ClassDeclarationSyntaxExtensions.GetPublicMethods(syntaxFake);
            object expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
    }
}