using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis;
using TestsGenerator.Core;

namespace Tests
{
    [TestClass]
    public class ClassDeclarationSyntaxExtensionsTests
    {
        [TestMethod]
        public void GetConstructorWithMaxArgumentsCountTest()
        {
            ClassDeclarationSyntax syntaxFake = default;
            ConstructorDeclarationSyntax actual = ClassDeclarationSyntaxExtensions.GetConstructorWithMaxArgumentsCount(syntaxFake);
            ConstructorDeclarationSyntax expected = default;
            Assert.AreEqual(actual, expected);
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void GetPublicMethodsTest()
        {
            ClassDeclarationSyntax syntaxFake = default;
            object actual = ClassDeclarationSyntaxExtensions.GetPublicMethods(syntaxFake);
            object expected = default;
            Assert.AreEqual(actual, expected);
            Assert.Fail("autogenerated");
        }
    }
}