using NUnit.Framework;
using Moq;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis;
using TestsGenerator.Core;

namespace Tests
{
    [TestFixture]
    public class CompilationUnitSyntaxExtensionsTests
    {
        [Test]
        public void GetClassesTest()
        {
            CompilationUnitSyntax rootFake = default;
            object actual = CompilationUnitSyntaxExtensions.GetClasses(rootFake);
            object expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
    }
}