using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis;
using TestsGenerator.Core;

namespace Tests
{
    [TestClass]
    public class MethodNameGeneratorTests
    {
        private MethodNameGenerator _testMethodNameGeneratorTests;
        public MethodNameGeneratorTests()
        {
            List<MethodDeclarationSyntax> methodsFake = default;
            _testMethodNameGeneratorTests = new MethodNameGenerator(methodsFake);
        }

        [TestMethod]
        public void GenerateMethodNameTest()
        {
            string methodNameFake = default;
            string actual = _testMethodNameGeneratorTests.GenerateMethodName(methodNameFake);
            string expected = default;
            Assert.AreEqual(actual, expected);
            Assert.Fail("autogenerated");
        }
    }
}