using NUnit.Framework;
using Moq;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis;
using TestsGenerator.Core;

namespace Tests
{
    [TestFixture]
    public class MethodNameGeneratorTests
    {
        private MethodNameGenerator _testMethodNameGeneratorTests;
        [SetUp]
        public void SetUp()
        {
            List<MethodDeclarationSyntax> methodsFake = default;
            _testMethodNameGeneratorTests = new MethodNameGenerator(methodsFake);
        }

        [Test]
        public void GenerateMethodNameTest()
        {
            string methodNameFake = default;
            string actual = _testMethodNameGeneratorTests.GenerateMethodName(methodNameFake);
            string expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
    }
}