using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis;
using TestsGenerator.Core;

namespace Tests
{
    [TestClass]
    public class TestGeneratorTests
    {
        private TestGenerator _testTestGeneratorTests;
        public TestGeneratorTests()
        {
            _testTestGeneratorTests = new TestGenerator();
        }

        [TestMethod]
        public void GenerateTest()
        {
            string fileFake = default;
            int generationTemplateFake = default;
            object actual = _testTestGeneratorTests.Generate(fileFake, generationTemplateFake);
            object expected = default;
            Assert.AreEqual(actual, expected);
            Assert.Fail("autogenerated");
        }
    }
}