using NUnit.Framework;
using Moq;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis;
using TestsGenerator.Core;

namespace Tests
{
    [TestFixture]
    public class TestGeneratorTests
    {
        private TestGenerator _testTestGeneratorTests;
        [SetUp]
        public void SetUp()
        {
            _testTestGeneratorTests = new TestGenerator();
        }

        [Test]
        public void GenerateTest()
        {
            string fileFake = default;
            int generationTemplateFake = default;
            object actual = _testTestGeneratorTests.Generate(fileFake, generationTemplateFake);
            object expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
    }
}